spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${KAFKA_GROUP_ID:consumer-product-user-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      user-api-url: ${USER_API_URL:http://localhost:8080/users}
      product-api-url: ${PRODUCT_API_URL:http://localhost:8081/products}
      topic: ${KAFKA_TOPIC:product-user-topic}
    listener:
      ack-mode: record
      concurrency: 1
      retry:
        enabled: true
        backoff:
          interval: 10000 # 10 segundos entre tentativas
          max-attempts: 100 # 0 = infinito

# Adicione outras configurações conforme necessário 

server:
  port: 8082 